
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 11;
  public static final int INT = 15;
  public static final int LBRACE = 7;
  public static final int INTLIT = 3;
  public static final int PLUS = 10;
  public static final int EOF = 0;
  public static final int IF = 12;
  public static final int ELSE = 13;
  public static final int error = 1;
  public static final int SEMICOLON = 9;
  public static final int RPAREN = 6;
  public static final int IDENTIFIER = 2;
  public static final int FLOATLIT = 4;
  public static final int RETURN = 14;
  public static final int RBRACE = 8;
  public static final int LPAREN = 5;
  public static final int FLOAT = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "INTLIT",
  "FLOATLIT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "IF",
  "ELSE",
  "RETURN",
  "INT",
  "FLOAT"
  };
}

